### ISSUE TITLE
Error after welcome message

### ISSUE THREAD

**Issue by kry0sc0pic** [klakho0400/J.A.R.V.I.S#3]
After JARVIS plays the welcome message i get an error , error log is attached.

`
Traceback (most recent call last):
  File "/home/krishaayjois/.local/lib/python3.6/site-packages/speech_recognition/__init__.py", line 108, in get_pyaudio
    import pyaudio
ModuleNotFoundError: No module named 'pyaudio'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "JARVIS.py", line 226, in <module>
    command = listentome()
  File "JARVIS.py", line 86, in listentome
    with sr.Microphone() as source:
  File "/home/krishaayjois/.local/lib/python3.6/site-packages/speech_recognition/__init__.py", line 79, in __init__
    self.pyaudio_module = self.get_pyaudio()
  File "/home/krishaayjois/.local/lib/python3.6/site-packages/speech_recognition/__init__.py", line 110, in get_pyaudio
    raise AttributeError("Could not find PyAudio; check installation")
AttributeError: Could not find PyAudio; check installation
`

**Comment by klakho0400** [comment]
sudo apt-get install python-pyaudio

**Comment by kry0sc0pic** [comment]
Thank You
